import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center items-center p-4">
          <Image src="logo.svg" alt="logo" width={80} height={36} />
          <h1 className="font-black p-4 text-4xl text-sky-600">edundytor</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
